export const testimonios = [
  {
    id: "maria",
    nombre: "María G.",
    texto: "Excelente servicio, el conductor fue muy amable y puntual. Definitivamente volveré a reservar.",
    fecha: "12 de junio de 2025",
    calificacion: 5,
    servicio: "Viaje en la ciudad",
  },
  {
    id: "carlos",
    nombre: "Carlos R.",
    texto: "Viajé con mi perrito y todo fue perfecto. El servicio pet friendly es lo mejor que he encontrado.",
    fecha: "5 de junio de 2025",
    calificacion: 4,
    servicio: "Viaje pet friendly",
  },
  {
    id: "laura",
    nombre: "Laura M.",
    texto: "Reservar fue súper fácil y rápido. El coche estaba limpio y el viaje fue cómodo.",
    fecha: "28 de mayo de 2025",
    calificacion: 5,
    servicio: "Viaje en la ciudad",
  },
  {
    id: "david",
    nombre: "David H.",
    texto: "El proceso fue sencillo y el conductor conocía bien la zona. Muy profesional.",
    fecha: "22 de mayo de 2025",
    calificacion: 4,
    servicio: "Viaje en la ciudad",
  },
  {
    id: "andrea",
    nombre: "Andrea P.",
    texto: "Me sentí segura durante todo el viaje. Muy recomendable para mujeres viajando solas.",
    fecha: "18 de mayo de 2025",
    calificacion: 5,
    servicio: "Viaje en la ciudad",
  },
  {
    id: "julio",
    nombre: "Julio S.",
    texto: "Excelente atención desde el primer mensaje. Todo salió mejor de lo esperado.",
    fecha: "10 de mayo de 2025",
    calificacion: 5,
    servicio: "Traslado al aeropuerto",
  },
  {
    id: "paula",
    nombre: "Paula M.",
    texto: "Muy buen servicio, me recogieron justo a tiempo y el conductor fue muy atento durante todo el trayecto.",
    fecha: "8 de mayo de 2025",
    calificacion: 5,
    servicio: "Traslado al aeropuerto",
  },
  {
    id: "roberto",
    nombre: "Roberto T.",
    texto: "Hice un viaje foráneo y fue excelente. Vehículo cómodo y buena comunicación. Repetiré sin duda.",
    fecha: "3 de mayo de 2025",
    calificacion: 5,
    servicio: "Viaje foráneo",
  },
  {
    id: "alejandra",
    nombre: "Alejandra V.",
    texto: "El conductor me ayudó con el equipaje y fue muy respetuoso. Un servicio muy humano y profesional.",
    fecha: "30 de abril de 2025",
    calificacion: 4,
    servicio: "Traslado al aeropuerto",
  },
  {
    id: "fernando",
    nombre: "Fernando C.",
    texto: "Fácil de reservar y buen seguimiento del viaje. La atención fue excelente.",
    fecha: "25 de abril de 2025",
    calificacion: 4,
    servicio: "Viaje en la ciudad",
  },
  {
    id: "liliana",
    nombre: "Liliana F.",
    texto: "Todo fue perfecto. Muy recomendable para viajes al aeropuerto, incluso en horarios complicados.",
    fecha: "22 de abril de 2025",
    calificacion: 5,
    servicio: "Traslado al aeropuerto",
  },
  {
    id: "miguel",
    nombre: "Miguel A.",
    texto: "Pedí un servicio para mis papás mayores y quedaron encantados con el trato y la puntualidad.",
    fecha: "18 de abril de 2025",
    calificacion: 5,
    servicio: "Viaje en la ciudad",
  },
];